/* Whitelist files which don't currently have unit tests, so that I
 * can get on with other things. */
#include "test2.H"

#include "test2.tmpl"

static testmodule __testuntested(
    "untested",
    list<filename>::mk("agentname.C",
                       "agentname.H",
                       "bytecount.C",
                       "bytecount.H",
                       "config.tmpl", /* Not even a C++ file */
                       "computecli.C",
                       "computefmt.C",
                       "computeservice.C",
                       "computespy.C",
                       "coordinator.C",
                       "coordinator.H",
                       "coordinatorcli.C",
                       "coordinatorservice.C",
                       "digest.C",
                       "digest.H",
                       "filesystemcli.C",
                       "filesystemservice.C",
                       "fundamentals.H",
                       "fuzzsched.C",
                       "fuzzsched.H",
                       "interfacetype.C",
                       "interfacetype.H",
                       "listenfd.C",
                       "listenfd.H",
                       "logging.C",
                       "logging.H",
                       "nnp.H",
                       "nnp.tmpl",
                       "main.H",
                       "main.C",
                       "profile.C",
                       "profile.H",
                       "proto2.C",
                       "proto2.H",
                       "quickcheck.C",
                       "quickcheck.H",
                       "socket.C",
                       "socket.H",
                       "spark.C",
                       "spark.H",
                       "spark.tmpl",
                       "shutdown.C",
                       "shutdown.H",
                       "storagecli.C",
                       "storagespy.C",
                       "streamstatus.C",
                       "streamstatus.H",
                       "tcpsocket.C",
                       "tcpsocket.H",
                       "test.C",
                       "test.H",
                       "test.tmpl",
                       "tid.C",
                       "tid.H",
                       "timestamp.C",
                       "timestamp.H",
                       "udpsocket.C",
                       "udpsocket.H",
                       "util.C",
                       "util.H",
                       "version.C",
                       "version.H",
                       "waitbox.C",
                       "waitbox.H",
                       "waitbox.tmpl"
        ),
    testmodule::LineCoverage(11_pc),
    testmodule::BranchCoverage(8_pc));
